### PR TITLE
Fixes for mypy.

### PR DESCRIPTION
**Pull request by cqc-alec**

### CODE REVIEW

**Review by Roland-djee — DISMISSED** [review]
Looking good.

**Review by Roland-djee — COMMENTED** [review]
Looking good but the failing tests seem to persist.

**Comment by cqc-alec** [comment]
> Looking good but the failing tests seem to persist.

It hasn't failed yet!

**Comment by Roland-djee** [comment]
> > Looking good but the failing tests seem to persist.
> 
> It hasn't failed yet!

It referred to the state prior to your last commit.

**Review by Roland-djee — APPROVED** [review]
LGTM.

**Pull request merged**
