### PR TITLE
Unpin from conan 2.0.5 and fix parsing scripts

### LINKED ISSUE #874: Update uses of `conan graph info xxxx --format json` for compatibility with conan 2.0.6

### PR DESCRIPTION
**Pull request by cqc-alec**
Closes #874 .

### CODE REVIEW

**Comment by cqc-alec** [comment]
Just noticed I missed the pytket build...

**Comment by cqc-alec** [comment]
> Just noticed I missed the pytket build...

Fixed this. By a coincidence the Python used to analyse the json in `pytket/setup.py` works for both the old and the new versions (which would explain why the build succeeded).

**Comment by trvto** [comment]
> > Just noticed I missed the pytket build...
> 
> Fixed this. By a coincidence the Python used to analyse the json in `pytket/setup.py` works for both the old and the new versions (which would explain why the build succeeded).

Ah ok. For me on Friday pytket builds were failing without 2.0.6, but I didn't spend much time investigating because pinning to 2.0.5 fixed it

**Comment by cqc-alec** [comment]
> Edit: Seems like they still are on the CI at least

Yes, oops -- will fix...

**Comment by cqc-alec** [comment]
Should be fixed now!

**Review by trvto — APPROVED** [review]

**Pull request merged**
