### PR TITLE
Ccache windows dynamic build

### PR DESCRIPTION
**Pull request by trvto**
`ccache 4.8.3` includes a bugfix that makes this possible 🥳

### CODE REVIEW

**Comment by trvto** [comment]
I couldn't figure out how to get the ccache version set dynamically. See the commented out step before the tket build step. If you have any ideas why its not working, please share 😄

**Comment by cqc-alec** [comment]
> I couldn't figure out how to get the ccache version set dynamically. See the commented out step before the tket build step. If you have any ideas why its not working, please share 😄

Is it because the command is running in Powershell and the syntax is different? In which case setting `shell: bash` for this step of the job may work? (I don't know Powershell well.)

**Comment by cqc-alec** [comment]
> Is it because the command is running in Powershell and the syntax is different? In which case setting `shell: bash` for this step of the job may work? (I don't know Powershell well.)

Sorry, I see you did that, ignore me.

**Comment by trvto** [comment]
> > I couldn't figure out how to get the ccache version set dynamically. See the commented out step before the tket build step. If you have any ideas why its not working, please share 😄
> 
> Is it because the command is running in Powershell and the syntax is different? In which case setting `shell: bash` for this step of the job may work? (I don't know Powershell well.)

I am pretty sure I was using `shell: bash`

**Comment by trvto** [comment]
Here you can see what happens: https://github.com/CQCL/tket/actions/runs/6502081399/job/17660502339

**Comment by cqc-alec** [comment]
> Here you can see what happens: https://github.com/CQCL/tket/actions/runs/6502081399/job/17660502339

I wonder if it's something to do with the escaped characters, and whether it would work with the backtick form, i.e.

```shell
ccache_bin="`ccache --shimgen-help | grep -ioE 'C:\\ProgramData\\Chocolatey\\lib\\ccache\\tools\\.+\\ccache.exe'`"
```

**Comment by cqc-alec** [comment]
> > Here you can see what happens: https://github.com/CQCL/tket/actions/runs/6502081399/job/17660502339
> 
> I wonder if it's something to do with the backslashes, and whether it would work with the backtick form, i.e.
> 
> ```shell
> ccache_bin="`ccache --shimgen-help | grep -ioE 'C:\\ProgramData\\Chocolatey\\lib\\ccache\\tools\\.+\\ccache.exe'`"
> ```

OK that didn't work. Sigh, this would be a lot easier with access to a Windows machine...

**Comment by trvto** [comment]
> 
> OK that didn't work. Sigh, this would be a lot easier with access to a Windows machine...

yep

**Comment by trvto** [comment]
Ok I found another route! Working now (at least a version change won't break anything).

**Review by cqc-alec — APPROVED** [review]
Thanks!

**Pull request merged**
