### PR TITLE
Updated flake.lock to bring symengine-0.12.0 into nix

### PR DESCRIPTION
**Pull request by jake-arkinstall**
… the patch file to fit

# Description

To keep the nix build in sync, symengine needed updating. Fortunately the flake tracks nixpkgs' master branch, which has had symengine 0.12 for a week. So a `nix flake update` handled that.

Additionally, as we patch symengine to have it expose symengine libraries through INTERFACE_LINK_LIBRARIES, the patch file needed adjusting to take into account the new symengine's `cmake/SymEngineConfig.cmake.in` file.

I have run the tests on my local linux machine.

# Related issues

N/A

# Checklist

- [x] I have performed a self-review of my code.
- [-] I have commented hard-to-understand parts of my code.
- [-] I have made corresponding changes to the public API documentation.
- [-] I have added tests that prove my fix is effective or that my feature works.
- [-] I have updated the changelog with any user-facing changes.

### CODE REVIEW

**Comment by cqc-alec** [comment]
Thanks. There was a CI failure on Ubuntu with my [draft PR](https://github.com/CQCL/tket/pull/1422) to update to symengine 0.12.0. (It seems the build just got cancelled, suggesting maybe a resource leak?) I'll wait till that's sorted out before merging this.

**Comment by cqc-alec** [comment]
@jake-arkinstall The symengine update is now on main, so this can be merged once the conflicts are resolved (just a version update needed I assume).

**Review by cqc-alec — COMMENTED** [review]
Fine to merge once conflicts are resolved.

**Comment by jake-arkinstall** [comment]
It should now be ready for merge.

**Comment by jake-arkinstall** [comment]
Note: a side effect of this update is that python is bumped to python3.12

**Pull request merged**
