### PR TITLE
docs: cherry-pick navbar fixes to `docmain`

### PR DESCRIPTION
**Pull request by CalMacCQ**
# Description

cherry-picking the commit from https://github.com/CQCL/tket/pull/1523 onto `docmain` so it will be cloned by the website.

Would be good to retire the `docmain` branch soon.

### CODE REVIEW

**Comment by CalMacCQ** [comment]
Canceled the CI checks. Accidentally selected `main` as the base branch so they started running

**Review by cqc-melf — APPROVED** [review]
The checks are not working, but I think it should still be okay to merge this. If you want to discuss this in details, please let me know.

**Comment by CalMacCQ** [comment]
> The checks are not working, but I think it should still be okay to merge this. If you want to discuss this in details, please let me know.

Do you mean the checks for the docs build specifically?

**Comment by cqc-melf** [comment]
I meant the normal tket checks, I saw your comment after I had written mine.

**Pull request merged**
