### PR TITLE
Renderer update

### PR DESCRIPTION
**Pull request by DNA386**
Bump renderer version to 0.6

-- Edit

This PR also includes some more recent bugfixes:
- Allow resizing the circuit display container on firefox
- Display container when viewing circuit in the browser is by default smaller

### CODE REVIEW

**Review by cqc-alec — DISMISSED** [review]
(mypy failure is unrelated)

**Comment by DNA386** [comment]
The new bugfix relates to large circuits making the jupyter notebook crash silently. Was particularly bad for the offline renderer since the html needs to include the circuit renderer code and dependencies, but this should resolve both.

**Review by CalMacCQ — APPROVED** [review]

**Comment by CalMacCQ** [comment]
Once the branch is updated could you double check that the `pytket.display` docs html pages looks okay? I can also do this if need be.

**Comment by DNA386** [comment]
Docs look fine, reference the correct package name.

**Comment by CalMacCQ** [comment]
Thanks, happy for this to be merged.

**Pull request merged**
