### PR TITLE
Don't build docs in release workflow.

### PR DESCRIPTION
**Pull request by cqc-alec**
# Description

Stop building the docs in the release workflow. They are already built in the PR workflow (to check that they build successfully); and are now published [separately](https://github.com/CQCL-DEV/tket-site/blob/main/.github/workflows/build_and_publish.yml) from the `docmain` branch.

# Checklist

- [x] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have updated the changelog with any user-facing changes.

### CODE REVIEW

**Comment by cqc-melf** [comment]
I think we are still using this to update https://cqcl.github.io/tket/pytket/api/ which is still the page of the docs google links to? I think it would be good to add a doc build for a push to `docmain` but that is not added yet?

**Comment by cqc-melf** [comment]
Or a better solution would be to put a 301 to redirect and remove everything?

**Comment by cqc-alec** [comment]
> Or a better solution would be to put a 301 to redirect and remove everything?

Yes, I think that's a good idea.

**Comment by cqc-alec** [comment]
> > Or a better solution would be to put a 301 to redirect and remove everything?
> 
> Yes, I think that's a good idea.

Will make a separate PR to do that.

**Comment by cqc-alec** [comment]
> > > Or a better solution would be to put a 301 to redirect and remove everything?
> > 
> > 
> > Yes, I think that's a good idea.
> 
> Will make a separate PR to do that.

#1213

**Review by cqc-melf — APPROVED** [review]

**Pull request merged**
