### PR TITLE
Update Windows compiler version.

### LINKED ISSUE #1246: Windows builds failing on CI
Windows builds are failing on CI with an error like:

```
 ERROR: test folder '""' not available, or it doesn't have a conanfile.py
Error: Process completed with exit code 1.
```

E.g. https://github.com/CQCL/tket/actions/runs/7842121951/job/21399817269?pr=1245

### PR DESCRIPTION
**Pull request by cqc-alec**
# Description

Testing here: https://github.com/CQCL/tket/actions/runs/9417545477/job/25942951717

# Related issues

Fixes #1246 .

# Checklist

- [x] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have updated the changelog with any user-facing changes.

### CODE REVIEW

**Review by cqc-melf — APPROVED** [review]

**Comment by cqc-melf** [comment]
Do you need to update the tket version?

**Comment by cqc-alec** [comment]
> Do you need to update the tket version?

Oh yes and also upload new versions of the dependencies. This will take a bit longer...

**Comment by cqc-alec** [comment]
> > Do you need to update the tket version?
> 
> Oh yes and also upload new versions of the dependencies. This will take a bit longer...

Although the build seems to succeed without updating the dependencies, so this may not be necessary.

**Comment by cqc-alec** [comment]
> > > Do you need to update the tket version?
> > 
> > 
> > Oh yes and also upload new versions of the dependencies. This will take a bit longer...
> 
> Although the build seems to succeed without updating the dependencies, so this may not be necessary.

From the logs in the test run:
```
 tkrng/0.3.3@tket/stable: Main binary package '9556ae6ff5e212da1d356fd43b69c9bbcd25365e' missing. Using compatible package 'a0de755b62b50efcb25b16ca1f8e7841d86f7d97': compiler.version=193
```
Sounds like it's not necessary to update the dependencies.

**Review by cqc-melf — APPROVED** [review]

**Pull request merged**
