### PR TITLE
Update emulator info and fix typo

### PR DESCRIPTION
**Pull request by CalMacCQ**
The extensions index shows the `H1-2E` emulator as still available which it is not. Updated the available emulators to `H1-1E` and `H2-1E` which I believe is correct.

### CODE REVIEW

**Comment by CalMacCQ** [comment]
Is there anything else that is missing from [this page](https://tket.quantinuum.com/extensions/)? Any more backends or extensions I should add?

Should pytket-phir be linked from here?

**Review by cqc-alec — DISMISSED** [review]
Not sure why the stubgen test is failing.

**Comment by cqc-alec** [comment]
> Not sure why the stubgen test is failing.

https://github.com/CQCL/tket/issues/1135

**Comment by CalMacCQ** [comment]
I've changed the file name from `extensions_index.rst` to `extensions.rst`.

This will make the URL `/extensions.html` instead of `extensions_index.html`. Changing this shouldn't break any existing links as we haven't updated them yet.

@cqc-melf and I were about to update the links from each of the extensions docs.

**Review by cqc-alec — APPROVED** [review]

**Pull request merged**
