### PR TITLE
Avoid blow-up of complexity when squashing symbolic circuits

### LINKED ISSUE #963: `FullPeepholeOptimise` with TK2 target runs forever on a small symbolic circuit
```python
from sympy import Symbol
from pytket.circuit import Circuit, OpType
from pytket.passes import FullPeepholeOptimise

a = Symbol("a")

c = Circuit(3)

c.add_gate(OpType.CX, [], [0, 1])
c.add_gate(OpType.Rz, [a], [0])
c.add_gate(OpType.CX, [], [0, 2])

FullPeepholeOptimise(target_2qb_gate=OpType.TK2).apply(c)
```

Consumes 100% CPU and does not return.

### PR DESCRIPTION
**Pull request by cqc-alec**
Fixes #963 .

### CODE REVIEW

**Comment by yao-cqc** [comment]
```python
from sympy import Symbol
from pytket.circuit import Circuit, OpType
from pytket.passes import SynthesiseTK
a = [Symbol(f"a_{i}") for i in range(100)]

c = Circuit(3)
for i in range(10):
    c.add_gate(OpType.CX, [], [0, 1])
    c.add_gate(OpType.Rz, [a[i]], [0])
    c.add_gate(OpType.CX, [], [1, 2])

SynthesiseTK().apply(c)
```

pytket 1.17 took 14.3s. The resulting circuit json is 2.7MB
this branch took 12.6s, but the expression is a lot simpler. 7kb

Not sure why it still takes that long to run.

**Comment by cqc-alec** [comment]
> Not sure why it still takes that long to run.

Hmm, yeah I'm surprised it took so long...

**Review by yao-cqc — COMMENTED** [review]
Thanks, I don't see any easy alternative to this...
Could you add this new argument to `compiler_pass_v1.json`?

**Comment by cqc-alec** [comment]
> Could you add this new argument to `compiler_pass_v1.json`?

Done.

**Review by yao-cqc — APPROVED** [review]

**Pull request merged**
