### PR TITLE
Use `lark` package instead of deprecated `lark-parser`

### LINKED ISSUE #1356: Updating `lark-parser` depedency to `lark`
Hi,

I am using `pytket` in a project where also `lark` is an dependency additionally to `lark-parser` that is required by `pytket`. Here, I face some compatibility issues resulting in errors since apparently having both `lark` and `lark-parser` installed with different versions is problematic. 

Therefore, I was wondering whether the (apparently deprecated) `lark-parser` dependency could be upgraded to `lark` as well.

### PR DESCRIPTION
**Pull request by cqc-alec**
# Description

Needs a couple of small tweaks to the qasm and quipper parsers.

# Related issues

Closes #1356 .

# Checklist

- [x] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have updated the changelog with any user-facing changes.

### CODE REVIEW

**Comment by jake-arkinstall** [comment]
Keeping the old hash can confuse nix and make it use the wrong package - it's usually best to give the hash an empty string on an update. Then the build fails, but it tells you what the hash should have been.

Additionally the latest versions of lark use pyproject formatting rather than a setup.py process, so buildPythonPackage needs to be told to use that. I've adjusted that and committed the change.

**Comment by cqc-alec** [comment]
> Keeping the old hash can confuse nix and make it use the wrong package - it's usually best to give the hash an empty string on an update. Then the build fails, but it tells you what the hash should have been.
> 
> Additionally the latest versions of lark use pyproject formatting rather than a setup.py process, so buildPythonPackage needs to be told to use that. I've adjusted that and committed the change.

@jake-arkinstall-quantinuum  Oops I think I just force-pushed over your change sorry. I was hoping it would tell me the correct hash. Please could you fix again? Thanks!

**Comment by jake-arkinstall** [comment]
> > Keeping the old hash can confuse nix and make it use the wrong package - it's usually best to give the hash an empty string on an update. Then the build fails, but it tells you what the hash should have been.
> > Additionally the latest versions of lark use pyproject formatting rather than a setup.py process, so buildPythonPackage needs to be told to use that. I've adjusted that and committed the change.
> 
> @jake-arkinstall-quantinuum Oops I think I just force-pushed over your change sorry. I was hoping it would tell me the correct hash. Please could you fix again? Thanks!

No worries, I should have warned you! I'll patch it now.

**Comment by cqc-melf** [comment]
Happy to approve this, are the nix questions sorted @jake-arkinstall @cqc-alec ?

**Comment by jake-arkinstall** [comment]
Yes, I am happy with the nix side here

**Review by cqc-melf — APPROVED** [review]

**Pull request merged**
