### PR TITLE
Skip non-module libraries when generating stubs.

### PR DESCRIPTION
**Pull request by cqc-alec**
For some reason `pkgutil` is including these libraries in its modules list (with latest version on Linux).

Also apply black formatting (first commit here).

### CODE REVIEW

**Review by trvto — APPROVED** [review]
👍

**Comment by trvto** [comment]
Could consider moving the mypy checks to macos-13 runners?

**Comment by trvto** [comment]
> Could consider moving the mypy checks to macos-13 runners?

Since they run much faster and would therefore also give earlier feedback

**Comment by cqc-alec** [comment]
> Could consider moving the mypy checks to macos-13 runners?

Yes, that would be good.

**Pull request merged**
