### PR TITLE
Use pyproject.toml setuptools_scm setup

### LINKED ISSUE #1045: Make pytket build work with setuptools>=8.0
See #1044 . Error was:

```
assert not write_to.is_absolute(), f"{write_to=}"
377
  AssertionError: write_to=PosixPath('/Users/alec/actions-runner2/_work/tket/tket/pytket/pytket/_version.py')
378
  error: subprocess-exited-with-error
```

But replacing `write_to` with a relative path led to runtime failures in the CI tests:

```
E   ModuleNotFoundError: No module named 'pytket._version'
```

### PR DESCRIPTION
**Pull request by trvto**
Fixes #1045

Had to bump tket version because the last push to develop that bumped it failed to build.

### CODE REVIEW

**Comment by cqc-alec** [comment]
Need to bump tket version because last push to `develop` failed to build.

**Comment by trvto** [comment]
Solution taken from here: https://github.com/pypa/setuptools_scm/tree/v7.1.0#setuppy-usage-deprecated. 

> Need to bump tket version because last push to `develop` failed to build.

Ok, thanks

**Comment by trvto** [comment]
Seems to work for normal CI builds (at least on macos-arm64), started the wheel builds from release action to make sure it works there too

**Review by cqc-alec — APPROVED** [review]
Great, thanks!

**Review by cqc-alec — CHANGES_REQUESTED** [review]
Oh no, tests still failing.

**Comment by trvto** [comment]
If I can't find a quick solution I'll approve your PR in the next 30 min

**Comment by trvto** [comment]
> If I can't find a quick solution I'll approve your PR in the next 30 min

One last try

**Comment by trvto** [comment]
Think it's working now, see wheel tests here: https://github.com/CQCL/tket/actions/runs/6251090539

**Review by cqc-alec — APPROVED** [review]

**Pull request merged**
