### PR TITLE
Main

### PR DESCRIPTION
**Pull request by cqc-melf**

### CODE REVIEW

**Comment by CalMacCQ** [comment]
Should the new ZX pass from Will appear in the changelog?  https://github.com/CQCL/tket/pull/769

**Review by cqc-alec — APPROVED** [review]

**Comment by cqc-alec** [comment]
> Should the new ZX pass from Will appear in the changelog? #769

Yes that should have gone in the changelog. We could add it retrospectively.

**Comment by cqc-melf** [comment]
Should we make a new PR + release to add that? I have found one small issues in the wasm documentation that could be updated together with this.

**Comment by cqc-alec** [comment]
> @cqc-alec Should we make a new PR + release to add that? I have found one small issues in the wasm documentation that could be updated together with this.

Not worth doing a new release, but these things could be fixed in a new PR.

**Pull request merged**
